name: user
permissions:
  id-token: write
  contents: read
on:
  push:
    branches: ["main"]
  pull_request:
    branches: [ "main" ]
    workflow_dispatch:
jobs:
  call-workflow-passing-data:
    uses: pdevops87/reusable-github-actions/.github/workflows/ci.yml@main
    with:
      appName: user
      apptype: node
